### ISSUE TITLE
haproxy-status3: Non-sense check

### ISSUE THREAD

**Issue by PointPubMedia** [Linuxfabrik/monitoring-plugins#571] opened 2022-04-21 18:13 UTC
Hi,

The data gathering some haproxy csv is having some part that need to be excluded from the check!

![image](https://user-images.githubusercontent.com/20915668/164525665-163ac36a-213e-47ce-af6a-e2db75d9d4f9.png)

The SERVERNAME " BACKEND " will always be /1.0 , that mean it will always generate a CRITICAL.

We spoke with Haproxy team (we have a business contract with them) and they told us, there's no way in the config to increase the /1.0 on for this one.

Maybe it should be remove from the "check" ?

**Comment by markuslf** [comment] 2022-04-21 19:31
I will have a look into it. 👍

**Comment by markuslf** [comment] 2022-06-17 14:14
It seems that you are referring to the `Sessions` column, and you get a CRIT, because 2 out of 1 possible sessions are used (which is weird).

I had a look at the plugin output in one of our datacenters. There, the output looks like this:
![image](https://user-images.githubusercontent.com/31855393/174315184-f08c4170-7377-4e85-9212-b3706cb5ae53.png)

So in BACKEND, our HAproxy supports up to 300 connections. In this special case, we are running HAProxy version 2.4.17, and check plugin version 2022021602. What do you use on your side?

**Comment by PointPubMedia** [comment] 2022-06-21 13:11
Markus,

We are using HAproxy EE 2.4r1 and the latest plugin...

But in our backend config, we have not set any limit... that's probably why we have a limit of "1"

**Comment by markuslf** [comment] 2022-06-30 14:30
Closing this issue. If this check warns about sessions, this is a HAProxy configuration issue. Unsetting or setting `maxconn` to appropriate values helps (as intended and expected).

**Closed by markuslf** 2022-06-30 14:30 UTC
Labels: bug
