### ISSUE TITLE
apache-httpd-status3: Host is stuck in "Waiting for more data (4)"

### ISSUE THREAD

**Issue by markuslf** [Linuxfabrik/monitoring-plugins#566] opened 2022-04-07 11:52 UTC
**Describe the bug**
Host is stuck showing `Waiting for more data (4).`. Nothing happens, even if .db file is deleted.

**To Reproduce**
001, mvc01

**Comment by NavidSassan** [comment] 2023-01-10 14:35
duplicate of #606

**Closed by NavidSassan** 2023-01-10 14:35 UTC
Labels: bug
